
services:
  pokedex-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app

  pokedex-frontend:
    build: ./pokedex-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:8080
    volumes:
      - ./pokedex-frontend:/app
      - /app/node_modules
    depends_on:
      - pokedex-backend
